#!/usr/bin/env bash
# A Bash script that prints a message every 2 seconds and handles SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
