#!/usr/bin/env bash
# Displays numbers 1-20 and prints superstitious notes using case

x=1
while [ $x -le 20 ]
do
  echo "$x"
  case $x in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  x=$((x + 1))
done
